Prevent AuthOptions from being extracted.
AuthOptions is an interface marked with `@DataObject`, which causes
problems with clojure when trying to compile such an interface with a
constructor:

```
java.lang.IllegalArgumentException: No matching ctor found for interface io.vertx.ext.auth.AuthOptions
```

By not extracting it, it doesn't get generated, and the problem is
fixed.